### ISSUE TITLE
Question : The difference between `PatchOperation.Replace` and `PatchOperation.Set`

### ISSUE THREAD

**Issue by shibayan** [AzureCosmosDB/PatchPrivatePreviewFeedbackGroup#11]
It seems that `Replace` and `Set` have the same effect, but what is the clear difference in processing?

**Comment by frigon** [comment]
@shibayan   you might look here for a similar comment: https://github.com/AzureCosmosDB/PatchPrivatePreviewFeedbackGroup/issues/2

I only see different I see is that on an object Set works as Upsert whereas Replace requires a property o preexist.

**Comment by saawasek** [comment]
@shibayan : Please refer to issue [https://github.com/AzureCosmosDB/PatchPrivatePreviewFeedbackGroup/issues/2](url)

**Comment by saawasek** [comment]
@shibayan : Please refer to the below issue for more details regarding the differences. Going ahead, we will update the Readme documentation too.
https://github.com/AzureCosmosDB/PatchPrivatePreviewFeedbackGroup/issues/2
