### ISSUE TITLE
Bug: Updating TTL on existing document with Time to Live enabled on container level fails

### ISSUE THREAD

**Issue by fmamic** [AzureCosmosDB/PatchPrivatePreviewFeedbackGroup#12]
As I understand, the only immutable property is id and partition key so updating TTL shouldn't be an issue.

I have container with following settings:
![image](https://user-images.githubusercontent.com/9407124/119969356-5e26a780-bfa6-11eb-95fc-032fd348a9cd.png)

Document is inserted already:
```json
{
    "id": "7afc26c28e71630ed6511ed8336ba30f4759cbcef43ae00a0b7d22ec3c25e4ba",
    "value": "7afc26c28e71630ed6511ed8336ba30f4759cbcef43ae00a0b7d22ec3c25e4ba",
    "isActive": false,
    "creationTimeStamp": "2021-03-27T01:36:27",
    "expirationTimeStamp": "2022-08-11T06:54:36+01:00",
    "ttl": 43325854,
    "metadata": {
        "NewField": "field",
        "NewField2": "field"
    },
    "providers": {
        "data": {
            "data": "1"
            }
        }
    },
    "_rid": "t6VoANztIgo0AAAAAAAAAA==",
    "_self": "dbs/t6VoAA==/colls/t6VoANztIgo=/docs/t6VoANztIgo0AAAAAAAAAA==/",
    "_etag": "\"00000000-0000-0000-53a6-d38efcd501d7\"",
    "_attachments": "attachments/",
    "randomNumber": 10000,
    "_ts": 1622195400
}
```

I'm trying to patch TTL:
```csharp
            var patchOperations = new List<PatchOperation>
            {
                PatchOperation.Add("/isActive", indicator.IsActive),
                PatchOperation.Add("/expirationTimeStamp", indicator.ExpirationTimeStamp),
                PatchOperation.Add("/metadata", indicator.Metadata),
                PatchOperation.Add("/ttl", 10000)
            };

            return patchOperations;
```

Exception doesn't say much:

![image](https://user-images.githubusercontent.com/9407124/119970112-400d7700-bfa7-11eb-92c7-179fac233490.png)

I'm testing on emulator with enabled patching (when I remove TTL patch it works without issue):
![image](https://user-images.githubusercontent.com/9407124/119970313-79de7d80-bfa7-11eb-9cb9-d40474bc541b.png)

**Comment by saawasek** [comment]
@fmamic: Thanks for trying it out. Actually "ttl" filed is treated as a special property and we are explicitly blocking Patch Operation on it as it could lead to unexpected results in Multimaster scenarios if used unintentionally. However, we can enable it on an individual account if needed.

**Comment by fmamic** [comment]
Thanks @saawasek. Is it possible to enable it on emulator?

**Comment by fmamic** [comment]
Just for FYI I will leave here how to enable TTL patching on emulator: 

```ps 
.\CosmosDB.Emulator.exe /overrides='enableJsonPatch:true;disablePatchForSystemProperties:false'
```

Again, this should be used only in non multi-master scenarios.
