### ISSUE TITLE
Question: Is there a patch or insert similar to existing Upsert functionality 

### ISSUE THREAD

**Issue by fmamic** [AzureCosmosDB/PatchPrivatePreviewFeedbackGroup#13]
Is it possible to avoid calling insert, catching exception and then calling patch because document exists?

This would be very similar to Upsert but instead of replacing document, it would do patching with given operations => 'Patchsert'.

**Comment by saawasek** [comment]
@fmamic : If I understood it currently, you want to try Patching document but are not sure if the document exists or not? If the document doesn't exists, it should be like upsert.
Answer >> Currently we do not support Creating a document with Patch API. We do have some plans in future and give more thought on this. Thanks for suggestion :)
