### ISSUE TITLE
Incorrect RFC document number for JSON Patch specification in README.md

### ISSUE THREAD

**Issue by WWeichselberger** [AzureCosmosDB/PatchPrivatePreviewFeedbackGroup#15]
The first question in the FAQ section of README.md refers to the JSON Patch specification as _RFC 6905_.
That's obviously a typo. The correct document number is **_RFC 6902_**.

**Comment by saawasek** [comment]
@WWeichselberger : Thanks for the suggestion and nice catch. We have fixed it.
