### ISSUE TITLE
How do we know the Patch API is already available/applied to our account?

### ISSUE THREAD

**Issue by moviapp** [AzureCosmosDB/PatchPrivatePreviewFeedbackGroup#18]
I filled the form asking to participate of this preview, but have no idea what comes next. Lol

Is there a place where a can check if it is already applied in my Azure Account/CosmosDB?

I am currently getting a 500 error when executing [Container].PatchItemAsync().

As a suggestion, you should have a "Lab" area with an improved experience for people trying out new things.

Thanks in advance!

**Comment by saawasek** [comment]
@moviapp : Sorry to hear this. Please let me know your subscription id and globaldb name. We will get back to you.

**Comment by moviapp** [comment]
@saawasek Subscription ID: 04617545-4bb2-4b66-a485-6a64f2f26721 and database global name: movi-database

**Comment by saawasek** [comment]
@moviapp : We have enabled Json Patch on the above account. Please try.

**Comment by moviapp** [comment]
@saawasek I confirm that now I can execute PatchItemAsync() successfully. 

Thanks!
