### ISSUE TITLE
keep getting error on PatchItemStreamAsync

### ISSUE THREAD

**Issue by ryancrawcour** [AzureCosmosDB/PatchPrivatePreviewFeedbackGroup#19]
here's my code - 

```csharp
    List<PatchOperation> patchOperations = new();
            patchOperations.Add(PatchOperation.Set("/ShippedDate", DateTime.Now));
            patchOperations.Add(PatchOperation.Set("/TotalDue", 0));
            
            using Stream stream = ToStream(patchOperations);
            using ResponseMessage responseMessage = await container.PatchItemStreamAsync(
                id: id,
                partitionKey: new PartitionKey(pk),
                patchOperations: patchOperations, 
                requestOptions: new PatchItemRequestOptions()
                {
                    EnableContentResponseOnWrite = false
                });

            if (responseMessage.IsSuccessStatusCode)
            {
                Console.WriteLine($"Request charge of patch operation: {responseMessage.Headers.RequestCharge}");
                totalRUs += responseMessage.Headers.RequestCharge;
            }
            else
            {
                Console.WriteLine($"Patch item from stream failed. Status code: {responseMessage.StatusCode} Message: {responseMessage.ErrorMessage}");
            }
```

i keep getting - 

Response status code does not indicate success: InternalServerError (500); Substatus: 0; ActivityId: 69466ed1-3eb2-4b49-a384-1a018682a743; Reason: (Message: {"Errors":["An unknown error occurred while processing this request. If the issue persists, please contact Azure Support: http://aka.ms/azure-support"]}
ActivityId: 69466ed1-3eb2-4b49-a384-1a018682a743, Request URI: /apps/c12190b1-ee9f-44a3-b9e8-98b49f9ce156/services/832ff889-1172-4ac3-8d74-ca9af49f0515/partitions/82dc3283-38c2-4a48-9d52-d23fac23594e/replicas/132675963043272040p/, RequestStats: Microsoft.Azure.Cosmos.Tracing.TraceData.ClientSideRequestStatisticsTraceDatum, SDK: Windows/10.0.19043 cosmos-netstandard-sdk/3.19.3);

"An unknown error occurred" isn't super useful. 
How do i determine what the error is?

**Comment by ryancrawcour** [comment]
i see this when i expand and dig around in the Diagnostics item on the response - 

![image](https://user-images.githubusercontent.com/38923605/123366107-ba8fdd80-d5cb-11eb-96bc-d6b11cf44110.png)

does this imply there is something wrong with my List<PatchOperations> object?

**Comment by ryancrawcour** [comment]
I even now changed my code to the following - 

```csharp
            try
            {
                _ = await container.PatchItemAsync<SalesOrder>(
                                id: orderId,
                                partitionKey: new PartitionKey(pk),
                                patchOperations: new[] { PatchOperation.Replace("/TotalDue", 0) });

            }
            catch(Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
```

and i still get the same 500 - Internal Server error with no indication of why it failed.

**Comment by saawasek** [comment]
@ryancrawcour : Please find the below explanation:
Since we are in Preview mode, Json Patch feature on a newly created collection gets enabled within 5-8 minutes after collection create. This will not happen after GA as it would be enabled by default.

We see that you are creating a collection and immediately applying patch on it. You can use existing created collection or have a delay between collection create and patch on the same one.

**Comment by ryancrawcour** [comment]
Thank you @saawasek ... this appears to have fixed the problem i was having. We should potentially update the preview documentation to include this caveat.

**Comment by saawasek** [comment]
@ryancrawcour: Thanks for the update on Readme page. I have merged your PR.
