### ISSUE TITLE
Documentation on Set vs Add or Replace

### ISSUE THREAD

**Issue by frigon** [AzureCosmosDB/PatchPrivatePreviewFeedbackGroup#2]
I don't see any clarification around the difference between and add, replace and set operators.  Do add and replace work like upsert operations or fail if a property exists with add or doesn't exist with replace?  If they fail then I assume that's why set is there to act as an upsert operation.  If they do not fail it's not clear how any of the operations are different from each other.

**Comment by onionhammer** [comment]
There should be some description of each operation in the initial readme, rather than just listing out the operations.

**Comment by saawasek** [comment]
@onionhammer : Thanks for the suggestion. We are planning to add this info in Readme too :)

**Comment by ryancrawcour** [comment]
please can you update the documentation for this as it appears it is a common piece of feedback while evaluating this preview. 
SET. REPLACE. ADD. are all quite similar, but subtly different.
