### ISSUE TITLE
Example of adding item to an array

### ISSUE THREAD

**Issue by ryancrawcour** [AzureCosmosDB/PatchPrivatePreviewFeedbackGroup#21]
Do we have an example of using Add to add an item to an array. 

My code
```csharp
            SalesOrderDetail lineItem = new()
            {
                OrderQty = 2,
                ProductId = 1,
                UnitPrice = 100,
                LineTotal = 200
            };
            
            ItemResponse<SalesOrder> response = await container.PatchItemAsync<SalesOrder>(
                id: orderId,
                partitionKey: new PartitionKey(pk),
                patchOperations: new[] { PatchOperation.Add("/Items/0/", lineItem) });
```

Gives me a strange JSON deserializing issue - 

Error: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'comosdb_patch_demo.SalesOrderDetail[]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'Documents[1].Items.OrderQty'., Message: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'comosdb_patch_demo.SalesOrderDetail[]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
**Path 'Documents[1].Items.OrderQty'.**

it appears to be trying to set something at Documents[1]
when i would expect it to be setting Document.Items[1] .... so i assume it's something to do with my JSON Path. 

even if i change the path to be "/Items/" i get the same error

**Comment by saawasek** [comment]
@ryancrawcour: I think the you are trying to add a new item whose Parent is an object. Check what is "Items" here. It should be array. If you consider the below example, SampleObject1 is valid object with "Items" as array for your request.
However, SampleObject2, can lead to failure.

SampleObject1
{
  Items:[]
}

SampleObject2
{
 Items:{"foo":"bar"}
}

**Comment by ryancrawcour** [comment]
thanks for the response @saawasek 

here is my document before the update - 
![image](https://user-images.githubusercontent.com/38923605/123709877-e1972980-d8c1-11eb-86f6-9e911f39a713.png)

here is my SalesOrder object - 
![image](https://user-images.githubusercontent.com/38923605/123709930-f2479f80-d8c1-11eb-9b61-c47413fa507e.png)

here is my PathOperation.Add code - 
![image](https://user-images.githubusercontent.com/38923605/123709996-0be8e700-d8c2-11eb-95b8-c1e245a16b91.png)

which throws this error - 
![image](https://user-images.githubusercontent.com/38923605/123710071-363aa480-d8c2-11eb-9908-c9392322f1d2.png)

hope this helps

**Comment by ryancrawcour** [comment]
if i change the path from "/Items/" to "/Items/0/" then the code runs but i get this - 

![image](https://user-images.githubusercontent.com/38923605/123710253-84e83e80-d8c2-11eb-882a-89ce1c2ba812.png)

which is not the desired outcome.

**Comment by ryancrawcour** [comment]
Ok, so by playing around with combinations of the path i found that "/Items/0" ( without the trailing / ) gives me this - 
![image](https://user-images.githubusercontent.com/38923605/123710445-ead4c600-d8c2-11eb-95e3-c00758df0b00.png)

which is the desired outcome. 
so it works.

I would imagine saying Add to /Items should be good enough. 
As per the description you provided of Add - 
"When we 'ADD' at any index, all existing elements in array would move right"

So because i have not specified 0 here it should be assumed. 
And therefore we should insert the new item at position 0 and move everything else to the right.

Is it possible to infer / default to position 0 if it was not specified?

i.e. if "/Items" or "/Items/" was provided and you can see it's an array, then assume i actually meant "/Items/0"

**Comment by ryancrawcour** [comment]
patch path is confusing as it's hard to know if you should supply a trailing / or not. 

e.g. "/Items/" vs "/Items" or "/Items/0" vs "/Items/0/"

I imagine it is going to lead to errors. 
is there any way we can get rid of this path and use something like the following instead - 

current syntax: "Items/0"
-vs-
proposed syntax: "Items[0]"

OR 

current syntax: "Items/0/OrderQty"
-vs-
proposed syntax: "Items[0].OrderQty"

and then let the SDK figure out what i actually mean

**Comment by saawasek** [comment]
@rjygraham: Thanks for the feedback and  suggestions regarding "path" syntax. 
There is already an open [issue ](https://github.com/AzureCosmosDB/PatchPrivatePreviewFeedbackGroup/issues/14) which talks about similar syntax. We will update you about it.

Regarding your concern about the trailing slash("/items/0/"), CosmosDB Json Patch is inspired by [RFC](https://datatracker.ietf.org/doc/html/rfc6902#appendix-A.2). 
According to standard Json protocol, object key can have a zero size. 
The trailing slash adds a new empty key within the scope of Parent and hence you see the below behavior.

![image](https://user-images.githubusercontent.com/82865256/123736306-84e63f80-d8be-11eb-86c5-e20ca8842c98.png)
