### ISSUE TITLE
Does any Cosmos DB Emulator version support this preview feature?

### ISSUE THREAD

**Issue by moviapp** [AzureCosmosDB/PatchPrivatePreviewFeedbackGroup#22]

**Comment by moviapp** [comment]
I was unable to find a preview version download of the Cosmos Emulator to test implementations with this new feature. 

Thanks in advance for any help.

**Comment by saawasek** [comment]
@moviapp: Yes, Patch feature is supported on CosmosDB emulator
Please check the last section of Readme. 
[Patch ](https://github.com/AzureCosmosDB/PatchPrivatePreviewFeedbackGroup#is-partial-document-update-supported-on-local-azure-cosmosdb-emulator)
