### ISSUE TITLE
Question: Does Patch work with stored procedures?

### ISSUE THREAD

**Issue by aorin123** [AzureCosmosDB/PatchPrivatePreviewFeedbackGroup#23]
Does patch work with stored procedures?  

For example can I use patch, instead of collection.replaceDocument in something like this:

https://github.com/Azure/azure-cosmosdb-js-server/blob/master/samples/stored-procedures/update.js

Basically change the query to just select the Id, rather than the full document, and then patch it.

If so are there any examples?

**Comment by saawasek** [comment]
@aorin123 : We do plan to support it and will update the docs soon. Thanks.
