### ISSUE TITLE
Feature Request: Allow non conflicting inserts to arrays,...

### ISSUE THREAD

**Issue by apollak** [AzureCosmosDB/PatchPrivatePreviewFeedbackGroup#8]
Referring to:
https://github.com/AzureCosmosDB/PatchPrivatePreviewFeedbackGroup/issues/6 

I would appreciate, if possible, that inserting (and only inserting) items at the end of an array with "/-"-Syntax  would never result in a conflict.

Thanks
 Andreas

**Comment by saawasek** [comment]
@apollak : We will take this into consideration going ahead. As of now since the scope of conflict in a SingleMaster setup is document, the above operation would result in conflict. This can be handled with retry as mentioned in another post.
