### ISSUE TITLE
JsonPath Support?

### ISSUE THREAD

**Issue by frigon** [AzureCosmosDB/PatchPrivatePreviewFeedbackGroup#9]
A JsonPath syntax (vs JsonPatch) would be very valuable.   Especially working with **Json.Net**, having to convert a JToken's path to the JsonPatch syntax is burdensome and accomplishes very little.

e.g. for the following object:
```
{
    myArray: [
         {
              title: 'hello'
         }
    ]
}
```
To update the nested title property:

JsonPatch syntax:   "myArray/0/title"
-vs-
JsonPath syntax: "myArray[0].title"

Since its not a complex find/replace... 
1.  Quick Solution A:  The SDK could handle this by either detecting the json path tokens like "[" or ".".
2.  Quick Solution B:  The SDK can have dedicated function for each operation (e.g. SetWithPath("myArray[0].title", "hi"))
3.  Deeper Solution:  Support at the REST API layer more natively.

The SDK solution is sufficient for my use case.

**Comment by saawasek** [comment]
@frigon:
Thanks for your feedback.
